# Generated by Django 4.2.4 on 2023-10-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.city'),
        ),
    ]
