# Generated by Django 4.2.4 on 2023-11-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_city_alter_subscription_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.CharField(default='', max_length=2),
        ),
    ]
