# Generated by Django 4.2.4 on 2023-12-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.city'),
        ),
    ]
