# Generated by Django 4.2.4 on 2024-02-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscription_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='city',
            new_name='city_id',
        ),
    ]
