# Generated by Django 4.2.4 on 2024-02-11 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_rename_name_city_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_data', to='subscription.city'),
        ),
    ]
