# Generated by Django 4.2.4 on 2024-02-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_alter_subscription_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country_code',
            field=models.CharField(max_length=2),
        ),
    ]
